//
// BulkUpdateJobStatus200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BulkUpdateJobStatus200Response: Sendable, Codable, ParameterConvertible, Hashable {

    public var updated: Double
    public var failed: [BulkUpdateJobStatus200ResponseFailedInner]

    public init(updated: Double, failed: [BulkUpdateJobStatus200ResponseFailedInner]) {
        self.updated = updated
        self.failed = failed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case updated
        case failed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(updated, forKey: .updated)
        try container.encode(failed, forKey: .failed)
    }
}

