//
// ChatRequestToolsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ChatRequestToolsInner: Sendable, Codable, ParameterConvertible, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case function = "function"
    }
    /** Specifies that this tool is a function */
    public var type: ModelType
    public var function: ChatRequestToolsInnerFunction

    public init(type: ModelType, function: ChatRequestToolsInnerFunction) {
        self.type = type
        self.function = function
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case function
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(function, forKey: .function)
    }
}

