//
// CreateCompletedWorkflowSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateCompletedWorkflowSchema: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: UUID?
    public var name: String
    public var companyId: String
    public var finalized: Bool?
    public var finalizedAt: Date?
    public var createdAt: Date?
    public var createdBy: String
    public var updatedAt: Date?
    public var typeRefId: String
    public var relatedObjectTypes: [CompletedWorkflowSchemaRelatedObjectTypesInner]?
    public var workflowInstanceId: UUID
    public var relatedWorkflowTemplateId: String
    public var auditTimeline: [CompletedWorkflowSchemaAuditTimelineInner]?
    public var relatedDataSynced: Bool?
    public var triggers: [CompletedWorkflowSchemaTriggersInner]?

    public init(id: UUID? = nil, name: String, companyId: String, finalized: Bool? = nil, finalizedAt: Date? = nil, createdAt: Date? = nil, createdBy: String, updatedAt: Date? = nil, typeRefId: String, relatedObjectTypes: [CompletedWorkflowSchemaRelatedObjectTypesInner]? = nil, workflowInstanceId: UUID, relatedWorkflowTemplateId: String, auditTimeline: [CompletedWorkflowSchemaAuditTimelineInner]? = nil, relatedDataSynced: Bool? = nil, triggers: [CompletedWorkflowSchemaTriggersInner]? = nil) {
        self.id = id
        self.name = name
        self.companyId = companyId
        self.finalized = finalized
        self.finalizedAt = finalizedAt
        self.createdAt = createdAt
        self.createdBy = createdBy
        self.updatedAt = updatedAt
        self.typeRefId = typeRefId
        self.relatedObjectTypes = relatedObjectTypes
        self.workflowInstanceId = workflowInstanceId
        self.relatedWorkflowTemplateId = relatedWorkflowTemplateId
        self.auditTimeline = auditTimeline
        self.relatedDataSynced = relatedDataSynced
        self.triggers = triggers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case companyId = "company_id"
        case finalized
        case finalizedAt = "finalized_at"
        case createdAt = "created_at"
        case createdBy = "created_by"
        case updatedAt = "updated_at"
        case typeRefId = "type_ref_id"
        case relatedObjectTypes = "related_object_types"
        case workflowInstanceId = "workflow_instance_id"
        case relatedWorkflowTemplateId = "related_workflow_template_id"
        case auditTimeline = "audit_timeline"
        case relatedDataSynced = "related_data_synced"
        case triggers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(companyId, forKey: .companyId)
        try container.encodeIfPresent(finalized, forKey: .finalized)
        try container.encodeIfPresent(finalizedAt, forKey: .finalizedAt)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encode(createdBy, forKey: .createdBy)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encode(typeRefId, forKey: .typeRefId)
        try container.encodeIfPresent(relatedObjectTypes, forKey: .relatedObjectTypes)
        try container.encode(workflowInstanceId, forKey: .workflowInstanceId)
        try container.encode(relatedWorkflowTemplateId, forKey: .relatedWorkflowTemplateId)
        try container.encodeIfPresent(auditTimeline, forKey: .auditTimeline)
        try container.encodeIfPresent(relatedDataSynced, forKey: .relatedDataSynced)
        try container.encodeIfPresent(triggers, forKey: .triggers)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CreateCompletedWorkflowSchema: Identifiable {}
