//
// CreateDeployedWorkflowSchemaEdgesInnerStyle.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateDeployedWorkflowSchemaEdgesInnerStyle: Sendable, Codable, ParameterConvertible, Hashable {

    public var strokeWidth: Double

    public init(strokeWidth: Double) {
        self.strokeWidth = strokeWidth
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case strokeWidth = "stroke_width"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(strokeWidth, forKey: .strokeWidth)
    }
}

