//
// CreateFile201Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateFile201Response: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: String
    public var uploadUrl: String

    public init(id: String, uploadUrl: String) {
        self.id = id
        self.uploadUrl = uploadUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case uploadUrl = "upload_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(uploadUrl, forKey: .uploadUrl)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CreateFile201Response: Identifiable {}
