//
// CreateApiKeyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateApiKeyRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public var role: String
    /** Days until expiration */
    public var expiration: Double?

    public init(role: String, expiration: Double? = nil) {
        self.role = role
        self.expiration = expiration
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case role
        case expiration
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(role, forKey: .role)
        try container.encodeIfPresent(expiration, forKey: .expiration)
    }
}

