//
// DeployedWorkflowSchemaObjectsInnerFieldsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DeployedWorkflowSchemaObjectsInnerFieldsInner: Sendable, Codable, ParameterConvertible, Hashable {

    public var displayName: String
    public var dynamicInputId: String
    public var arraySubType: String?
    public var jsonSchema: String?
    public var jsonSchemaId: String?
    public var arrayCloneableSubType: String?
    public var dynamicOutputId: String
    public var fieldId: String
    public var linkedObjectDisplayName: String?
    public var linkedObjectId: String?
    public var linkedObjectName: String?
    public var linkedObjectRevision: Double?
    public var name: String
    public var type: String
    public var statusOptions: [String]?
    public var fileInformation: DeployedWorkflowSchemaObjectsInnerFieldsInnerFileInformation?
    public var outputConnections: [DeployedWorkflowSchemaComponentsInnerOutputsInnerOutputConnectionsInner]?

    public init(displayName: String, dynamicInputId: String, arraySubType: String? = nil, jsonSchema: String? = nil, jsonSchemaId: String? = nil, arrayCloneableSubType: String? = nil, dynamicOutputId: String, fieldId: String, linkedObjectDisplayName: String? = nil, linkedObjectId: String? = nil, linkedObjectName: String? = nil, linkedObjectRevision: Double? = nil, name: String, type: String, statusOptions: [String]? = nil, fileInformation: DeployedWorkflowSchemaObjectsInnerFieldsInnerFileInformation? = nil, outputConnections: [DeployedWorkflowSchemaComponentsInnerOutputsInnerOutputConnectionsInner]? = nil) {
        self.displayName = displayName
        self.dynamicInputId = dynamicInputId
        self.arraySubType = arraySubType
        self.jsonSchema = jsonSchema
        self.jsonSchemaId = jsonSchemaId
        self.arrayCloneableSubType = arrayCloneableSubType
        self.dynamicOutputId = dynamicOutputId
        self.fieldId = fieldId
        self.linkedObjectDisplayName = linkedObjectDisplayName
        self.linkedObjectId = linkedObjectId
        self.linkedObjectName = linkedObjectName
        self.linkedObjectRevision = linkedObjectRevision
        self.name = name
        self.type = type
        self.statusOptions = statusOptions
        self.fileInformation = fileInformation
        self.outputConnections = outputConnections
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case displayName = "display_name"
        case dynamicInputId = "dynamic_input_id"
        case arraySubType = "array_sub_type"
        case jsonSchema = "json_schema"
        case jsonSchemaId = "json_schema_id"
        case arrayCloneableSubType = "array_cloneable_sub_type"
        case dynamicOutputId = "dynamic_output_id"
        case fieldId = "field_id"
        case linkedObjectDisplayName = "linked_object_display_name"
        case linkedObjectId = "linked_object_id"
        case linkedObjectName = "linked_object_name"
        case linkedObjectRevision = "linked_object_revision"
        case name
        case type
        case statusOptions = "status_options"
        case fileInformation = "file_information"
        case outputConnections = "output_connections"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(displayName, forKey: .displayName)
        try container.encode(dynamicInputId, forKey: .dynamicInputId)
        try container.encodeIfPresent(arraySubType, forKey: .arraySubType)
        try container.encodeIfPresent(jsonSchema, forKey: .jsonSchema)
        try container.encodeIfPresent(jsonSchemaId, forKey: .jsonSchemaId)
        try container.encodeIfPresent(arrayCloneableSubType, forKey: .arrayCloneableSubType)
        try container.encode(dynamicOutputId, forKey: .dynamicOutputId)
        try container.encode(fieldId, forKey: .fieldId)
        try container.encodeIfPresent(linkedObjectDisplayName, forKey: .linkedObjectDisplayName)
        try container.encodeIfPresent(linkedObjectId, forKey: .linkedObjectId)
        try container.encodeIfPresent(linkedObjectName, forKey: .linkedObjectName)
        try container.encodeIfPresent(linkedObjectRevision, forKey: .linkedObjectRevision)
        try container.encode(name, forKey: .name)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(statusOptions, forKey: .statusOptions)
        try container.encodeIfPresent(fileInformation, forKey: .fileInformation)
        try container.encodeIfPresent(outputConnections, forKey: .outputConnections)
    }
}

