//
// FileInformationSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FileInformationSchema: Sendable, Codable, ParameterConvertible, Hashable {

    public var fileName: String?
    public var fileUrl: String?
    public var storageProvider: String?
    public var storageAuthProviderRefId: String?
    public var storageAuthProviderName: String?
    public var fileType: String
    public var fileExtension: String?
    public var fileSize: Double?
    public var oneWaySync: Bool

    public init(fileName: String? = nil, fileUrl: String? = nil, storageProvider: String? = nil, storageAuthProviderRefId: String? = nil, storageAuthProviderName: String? = nil, fileType: String, fileExtension: String? = nil, fileSize: Double? = nil, oneWaySync: Bool) {
        self.fileName = fileName
        self.fileUrl = fileUrl
        self.storageProvider = storageProvider
        self.storageAuthProviderRefId = storageAuthProviderRefId
        self.storageAuthProviderName = storageAuthProviderName
        self.fileType = fileType
        self.fileExtension = fileExtension
        self.fileSize = fileSize
        self.oneWaySync = oneWaySync
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fileName = "file_name"
        case fileUrl = "file_url"
        case storageProvider = "storage_provider"
        case storageAuthProviderRefId = "storage_auth_provider_ref_id"
        case storageAuthProviderName = "storage_auth_provider_name"
        case fileType = "file_type"
        case fileExtension = "file_extension"
        case fileSize = "file_size"
        case oneWaySync = "one_way_sync"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(fileName, forKey: .fileName)
        try container.encodeIfPresent(fileUrl, forKey: .fileUrl)
        try container.encodeIfPresent(storageProvider, forKey: .storageProvider)
        try container.encodeIfPresent(storageAuthProviderRefId, forKey: .storageAuthProviderRefId)
        try container.encodeIfPresent(storageAuthProviderName, forKey: .storageAuthProviderName)
        try container.encode(fileType, forKey: .fileType)
        try container.encodeIfPresent(fileExtension, forKey: .fileExtension)
        try container.encodeIfPresent(fileSize, forKey: .fileSize)
        try container.encode(oneWaySync, forKey: .oneWaySync)
    }
}

