//
// GetAccountAnalytics200ResponseUsersInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetAccountAnalytics200ResponseUsersInner: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: String
    public var email: String
    public var name: String?
    public var appVersion: String?
    public var lastSeenAt: String?
    public var sessionsCount: Double
    public var platform: String?
    public var deviceType: String?
    public var createdAt: String
    public var customAttributes: [String: JSONValue]?

    public init(id: String, email: String, name: String?, appVersion: String?, lastSeenAt: String?, sessionsCount: Double, platform: String?, deviceType: String?, createdAt: String, customAttributes: [String: JSONValue]? = nil) {
        self.id = id
        self.email = email
        self.name = name
        self.appVersion = appVersion
        self.lastSeenAt = lastSeenAt
        self.sessionsCount = sessionsCount
        self.platform = platform
        self.deviceType = deviceType
        self.createdAt = createdAt
        self.customAttributes = customAttributes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case email
        case name
        case appVersion = "app_version"
        case lastSeenAt = "last_seen_at"
        case sessionsCount = "sessions_count"
        case platform
        case deviceType = "device_type"
        case createdAt = "created_at"
        case customAttributes = "custom_attributes"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(email, forKey: .email)
        try container.encode(name, forKey: .name)
        try container.encode(appVersion, forKey: .appVersion)
        try container.encode(lastSeenAt, forKey: .lastSeenAt)
        try container.encode(sessionsCount, forKey: .sessionsCount)
        try container.encode(platform, forKey: .platform)
        try container.encode(deviceType, forKey: .deviceType)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(customAttributes, forKey: .customAttributes)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension GetAccountAnalytics200ResponseUsersInner: Identifiable {}
