//
// GetAccountAnalytics200ResponseSessionTrendsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetAccountAnalytics200ResponseSessionTrendsInner: Sendable, Codable, ParameterConvertible, Hashable {

    public var date: String
    public var sessions: Double
    public var activeUsers: Double

    public init(date: String, sessions: Double, activeUsers: Double) {
        self.date = date
        self.sessions = sessions
        self.activeUsers = activeUsers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case sessions
        case activeUsers = "active_users"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(date, forKey: .date)
        try container.encode(sessions, forKey: .sessions)
        try container.encode(activeUsers, forKey: .activeUsers)
    }
}

