//
// GetDailyUsage200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetDailyUsage200Response: Sendable, Codable, ParameterConvertible, Hashable {

    public var dailyUsage: [GetDailyUsage200ResponseDailyUsageInner]
    public var summary: GetDailyUsage200ResponseSummary

    public init(dailyUsage: [GetDailyUsage200ResponseDailyUsageInner], summary: GetDailyUsage200ResponseSummary) {
        self.dailyUsage = dailyUsage
        self.summary = summary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dailyUsage = "daily_usage"
        case summary
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(dailyUsage, forKey: .dailyUsage)
        try container.encode(summary, forKey: .summary)
    }
}

