//
// GetExecutionSummaryByType200ResponseImportRecentExecutionsInnerTrigger.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetExecutionSummaryByType200ResponseImportRecentExecutionsInnerTrigger: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: String
    public var name: String
    public var templateId: String?

    public init(id: String, name: String, templateId: String?) {
        self.id = id
        self.name = name
        self.templateId = templateId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case templateId = "template_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(templateId, forKey: .templateId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension GetExecutionSummaryByType200ResponseImportRecentExecutionsInnerTrigger: Identifiable {}
