//
// GetExecutionSummaryByType200ResponseImport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetExecutionSummaryByType200ResponseImport: Sendable, Codable, ParameterConvertible, Hashable {

    public var stats: GetExportExecutions200ResponseSummary
    public var recentExecutions: [GetExecutionSummaryByType200ResponseImportRecentExecutionsInner]

    public init(stats: GetExportExecutions200ResponseSummary, recentExecutions: [GetExecutionSummaryByType200ResponseImportRecentExecutionsInner]) {
        self.stats = stats
        self.recentExecutions = recentExecutions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case stats
        case recentExecutions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(stats, forKey: .stats)
        try container.encode(recentExecutions, forKey: .recentExecutions)
    }
}

