//
// GetJobStatistics200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetJobStatistics200Response: Sendable, Codable, ParameterConvertible, Hashable {

    public var total: Double
    public var byStatus: GetJobStatistics200ResponseByStatus
    public var byConfiguration: [GetJobStatistics200ResponseByConfigurationInner]
    public var recentActivity: [GetJobStatistics200ResponseRecentActivityInner]

    public init(total: Double, byStatus: GetJobStatistics200ResponseByStatus, byConfiguration: [GetJobStatistics200ResponseByConfigurationInner], recentActivity: [GetJobStatistics200ResponseRecentActivityInner]) {
        self.total = total
        self.byStatus = byStatus
        self.byConfiguration = byConfiguration
        self.recentActivity = recentActivity
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case byStatus
        case byConfiguration
        case recentActivity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(total, forKey: .total)
        try container.encode(byStatus, forKey: .byStatus)
        try container.encode(byConfiguration, forKey: .byConfiguration)
        try container.encode(recentActivity, forKey: .recentActivity)
    }
}

