//
// GetJobs200ResponseJobsInnerMetadataExportBatchesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetJobs200ResponseJobsInnerMetadataExportBatchesInner: Sendable, Codable, ParameterConvertible, Hashable {

    public var batchId: String
    public var startedAt: String
    public var queuedCount: Double

    public init(batchId: String, startedAt: String, queuedCount: Double) {
        self.batchId = batchId
        self.startedAt = startedAt
        self.queuedCount = queuedCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case batchId = "batch_id"
        case startedAt = "started_at"
        case queuedCount = "queued_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(batchId, forKey: .batchId)
        try container.encode(startedAt, forKey: .startedAt)
        try container.encode(queuedCount, forKey: .queuedCount)
    }
}

