//
// GetJobs200ResponseJobsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetJobs200ResponseJobsInner: Sendable, Codable, ParameterConvertible, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case pending = "pending"
        case inProgress = "in_progress"
        case completed = "completed"
        case cancelled = "cancelled"
    }
    public var id: UUID
    public var name: String
    public var description: String?
    public var configurationId: UUID?
    public var status: Status
    public var assignedTo: String?
    public var location: String?
    public var metadata: GetJobs200ResponseJobsInnerMetadata
    public var importExecutionId: UUID?
    public var createdBy: String?
    public var createdAt: Date
    public var updatedAt: Date

    public init(id: UUID, name: String, description: String?, configurationId: UUID?, status: Status, assignedTo: String?, location: String?, metadata: GetJobs200ResponseJobsInnerMetadata, importExecutionId: UUID?, createdBy: String?, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.name = name
        self.description = description
        self.configurationId = configurationId
        self.status = status
        self.assignedTo = assignedTo
        self.location = location
        self.metadata = metadata
        self.importExecutionId = importExecutionId
        self.createdBy = createdBy
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case configurationId = "configuration_id"
        case status
        case assignedTo = "assigned_to"
        case location
        case metadata
        case importExecutionId = "import_execution_id"
        case createdBy = "created_by"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encode(configurationId, forKey: .configurationId)
        try container.encode(status, forKey: .status)
        try container.encode(assignedTo, forKey: .assignedTo)
        try container.encode(location, forKey: .location)
        try container.encode(metadata, forKey: .metadata)
        try container.encode(importExecutionId, forKey: .importExecutionId)
        try container.encode(createdBy, forKey: .createdBy)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension GetJobs200ResponseJobsInner: Identifiable {}
