//
// GetModelConversionJobsFiltersParameter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetModelConversionJobsFiltersParameter: Sendable, Codable, ParameterConvertible, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case pending = "pending"
        case running = "running"
        case completed = "completed"
        case failed = "failed"
    }
    public var status: [Status]
    public var originModelId: String?

    public init(status: [Status], originModelId: String? = nil) {
        self.status = status
        self.originModelId = originModelId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case originModelId = "origin_model_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(originModelId, forKey: .originModelId)
    }
}

