//
// GetManyDataObjectTemplatesFiltersParameter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetManyDataObjectTemplatesFiltersParameter: Sendable, Codable, ParameterConvertible, Hashable {

    public var isTemplate: Bool?

    public init(isTemplate: Bool? = nil) {
        self.isTemplate = isTemplate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isTemplate = "is_template"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(isTemplate, forKey: .isTemplate)
    }
}

