//
// GetNotificationsRequestFilters.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetNotificationsRequestFilters: Sendable, Codable, ParameterConvertible, Hashable {

    public var workflowId: String

    public init(workflowId: String) {
        self.workflowId = workflowId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case workflowId = "workflow_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(workflowId, forKey: .workflowId)
    }
}

