//
// GetOneDataObjectTemplate400Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetOneDataObjectTemplate400Response: Sendable, Codable, ParameterConvertible, Hashable {

    public var message: String
    public var fieldErrors: [String: [String]]?

    public init(message: String, fieldErrors: [String: [String]]? = nil) {
        self.message = message
        self.fieldErrors = fieldErrors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case fieldErrors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encodeIfPresent(fieldErrors, forKey: .fieldErrors)
    }
}

