//
// GetPlatformMetrics200ResponseInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetPlatformMetrics200ResponseInner: Sendable, Codable, ParameterConvertible, Hashable {

    public var companyName: String
    public var companyId: String
    public var totalMeasurements: Double
    public var last30DaysMeasurements: Double
    public var firstMeasurementDate: String?
    public var lastMeasurementDate: String?

    public init(companyName: String, companyId: String, totalMeasurements: Double, last30DaysMeasurements: Double, firstMeasurementDate: String?, lastMeasurementDate: String?) {
        self.companyName = companyName
        self.companyId = companyId
        self.totalMeasurements = totalMeasurements
        self.last30DaysMeasurements = last30DaysMeasurements
        self.firstMeasurementDate = firstMeasurementDate
        self.lastMeasurementDate = lastMeasurementDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case companyName = "company_name"
        case companyId = "company_id"
        case totalMeasurements = "total_measurements"
        case last30DaysMeasurements = "last_30_days_measurements"
        case firstMeasurementDate = "first_measurement_date"
        case lastMeasurementDate = "last_measurement_date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(companyName, forKey: .companyName)
        try container.encode(companyId, forKey: .companyId)
        try container.encode(totalMeasurements, forKey: .totalMeasurements)
        try container.encode(last30DaysMeasurements, forKey: .last30DaysMeasurements)
        try container.encode(firstMeasurementDate, forKey: .firstMeasurementDate)
        try container.encode(lastMeasurementDate, forKey: .lastMeasurementDate)
    }
}

