//
// GetSuggestions200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetSuggestions200Response: Sendable, Codable, ParameterConvertible, Hashable {

    public var suggestions: [GetSuggestions200ResponseSuggestionsInner]

    public init(suggestions: [GetSuggestions200ResponseSuggestionsInner]) {
        self.suggestions = suggestions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case suggestions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(suggestions, forKey: .suggestions)
    }
}

