//
// GetTriggerSecrets200ResponseInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetTriggerSecrets200ResponseInner: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: UUID
    public var name: String
    public var description: String?
    public var encryptedValue: String?
    public var type: String
    public var createdAt: Date?
    public var createdBy: String?
    public var updatedAt: Date?
    public var updatedBy: String?

    public init(id: UUID, name: String, description: String?, encryptedValue: String? = nil, type: String, createdAt: Date?, createdBy: String?, updatedAt: Date?, updatedBy: String?) {
        self.id = id
        self.name = name
        self.description = description
        self.encryptedValue = encryptedValue
        self.type = type
        self.createdAt = createdAt
        self.createdBy = createdBy
        self.updatedAt = updatedAt
        self.updatedBy = updatedBy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case encryptedValue = "encrypted_value"
        case type
        case createdAt = "created_at"
        case createdBy = "created_by"
        case updatedAt = "updated_at"
        case updatedBy = "updated_by"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encodeIfPresent(encryptedValue, forKey: .encryptedValue)
        try container.encode(type, forKey: .type)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(createdBy, forKey: .createdBy)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(updatedBy, forKey: .updatedBy)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension GetTriggerSecrets200ResponseInner: Identifiable {}
