//
// GetTriggerTemplates200ResponseInnerConfigParams.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetTriggerTemplates200ResponseInnerConfigParams: Sendable, Codable, ParameterConvertible, Hashable {

    public var parameters: [GetTriggerTemplates200ResponseInnerConfigParamsParametersInner]

    public init(parameters: [GetTriggerTemplates200ResponseInnerConfigParamsParametersInner]) {
        self.parameters = parameters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case parameters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(parameters, forKey: .parameters)
    }
}

