//
// GetUserEvents200ResponseEventsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct GetUserEvents200ResponseEventsInner: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: String
    public var eventName: String
    public var userId: String
    public var userEmail: String
    public var createdAt: String
    public var metadata: [String: JSONValue]?

    public init(id: String, eventName: String, userId: String, userEmail: String, createdAt: String, metadata: [String: JSONValue]? = nil) {
        self.id = id
        self.eventName = eventName
        self.userId = userId
        self.userEmail = userEmail
        self.createdAt = createdAt
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case eventName = "event_name"
        case userId = "user_id"
        case userEmail = "user_email"
        case createdAt = "created_at"
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(eventName, forKey: .eventName)
        try container.encode(userId, forKey: .userId)
        try container.encode(userEmail, forKey: .userEmail)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(metadata, forKey: .metadata)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension GetUserEvents200ResponseEventsInner: Identifiable {}
