//
// HealthCheck200ResponseContainer.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HealthCheck200ResponseContainer: Sendable, Codable, ParameterConvertible, Hashable {

    public var available: Bool
    public var id: String?
    public var launching: Bool
    public var socketConnected: Bool
    public var lastHeartbeat: Double?

    public init(available: Bool, id: String?, launching: Bool, socketConnected: Bool, lastHeartbeat: Double?) {
        self.available = available
        self.id = id
        self.launching = launching
        self.socketConnected = socketConnected
        self.lastHeartbeat = lastHeartbeat
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case available
        case id
        case launching
        case socketConnected = "socket_connected"
        case lastHeartbeat = "last_heartbeat"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(available, forKey: .available)
        try container.encode(id, forKey: .id)
        try container.encode(launching, forKey: .launching)
        try container.encode(socketConnected, forKey: .socketConnected)
        try container.encode(lastHeartbeat, forKey: .lastHeartbeat)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension HealthCheck200ResponseContainer: Identifiable {}
