//
// HealthCheck200ResponseDurableObject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HealthCheck200ResponseDurableObject: Sendable, Codable, ParameterConvertible, Hashable {

    public var id: String?
    public var userContext: Bool

    public init(id: String?, userContext: Bool) {
        self.id = id
        self.userContext = userContext
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case userContext = "user_context"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(userContext, forKey: .userContext)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension HealthCheck200ResponseDurableObject: Identifiable {}
