//
// HealthCheck200ResponseExecution.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HealthCheck200ResponseExecution: Sendable, Codable, ParameterConvertible, Hashable {

    public enum Method: String, Sendable, Codable, CaseIterable {
        case single = "single"
        case multiple = "multiple"
    }
    public var running: Bool
    public var currentExecutionId: String?
    public var method: Method

    public init(running: Bool, currentExecutionId: String?, method: Method) {
        self.running = running
        self.currentExecutionId = currentExecutionId
        self.method = method
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case running
        case currentExecutionId = "current_execution_id"
        case method
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(running, forKey: .running)
        try container.encode(currentExecutionId, forKey: .currentExecutionId)
        try container.encode(method, forKey: .method)
    }
}

