//
// InsertTriggerSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InsertTriggerSchema: Sendable, Codable, ParameterConvertible, Hashable {

    public static let executionWaitTimeRule = NumericRule<Int>(minimum: -2147483648, exclusiveMinimum: false, maximum: 2147483647, exclusiveMaximum: false, multipleOf: nil)
    public var id: UUID?
    public var name: String
    public var description: String?
    public var type: String
    public var enabled: Bool?
    public var archived: Bool?
    public var code: String?
    public var runtime: String
    public var schedule: String?
    public var executionType: String?
    public var executionWaitTime: Int?
    public var environmentVariables: [String: String]?
    public var resourceLimits: InsertTriggerSchemaResourceLimits?
    public var inputSchema: InsertTriggerSchemaInputSchema?
    public var outputSchema: InsertTriggerSchemaInputSchema?
    public var state: [String: JSONValue]?
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(id: UUID? = nil, name: String, description: String? = nil, type: String, enabled: Bool? = nil, archived: Bool? = nil, code: String? = nil, runtime: String, schedule: String? = nil, executionType: String? = nil, executionWaitTime: Int? = nil, environmentVariables: [String: String]?, resourceLimits: InsertTriggerSchemaResourceLimits?, inputSchema: InsertTriggerSchemaInputSchema?, outputSchema: InsertTriggerSchemaInputSchema?, state: [String: JSONValue]?, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.id = id
        self.name = name
        self.description = description
        self.type = type
        self.enabled = enabled
        self.archived = archived
        self.code = code
        self.runtime = runtime
        self.schedule = schedule
        self.executionType = executionType
        self.executionWaitTime = executionWaitTime
        self.environmentVariables = environmentVariables
        self.resourceLimits = resourceLimits
        self.inputSchema = inputSchema
        self.outputSchema = outputSchema
        self.state = state
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case type
        case enabled
        case archived
        case code
        case runtime
        case schedule
        case executionType = "execution_type"
        case executionWaitTime = "execution_wait_time"
        case environmentVariables = "environment_variables"
        case resourceLimits = "resource_limits"
        case inputSchema = "input_schema"
        case outputSchema = "output_schema"
        case state
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(archived, forKey: .archived)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encode(runtime, forKey: .runtime)
        try container.encodeIfPresent(schedule, forKey: .schedule)
        try container.encodeIfPresent(executionType, forKey: .executionType)
        try container.encodeIfPresent(executionWaitTime, forKey: .executionWaitTime)
        try container.encode(environmentVariables, forKey: .environmentVariables)
        try container.encode(resourceLimits, forKey: .resourceLimits)
        try container.encode(inputSchema, forKey: .inputSchema)
        try container.encode(outputSchema, forKey: .outputSchema)
        try container.encode(state, forKey: .state)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension InsertTriggerSchema: Identifiable {}
