//
// QueryDataObjectFields200ResponseInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct QueryDataObjectFields200ResponseInner: Sendable, Codable, ParameterConvertible, Hashable {

    public var dataObjectId: String
    public var dataObjectTemplateNameId: String
    public var updatedAt: Date
    public var fields: [String: JSONValue]

    public init(dataObjectId: String, dataObjectTemplateNameId: String, updatedAt: Date, fields: [String: JSONValue]) {
        self.dataObjectId = dataObjectId
        self.dataObjectTemplateNameId = dataObjectTemplateNameId
        self.updatedAt = updatedAt
        self.fields = fields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dataObjectId = "data_object_id"
        case dataObjectTemplateNameId = "data_object_template_name_id"
        case updatedAt = "updated_at"
        case fields
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(dataObjectId, forKey: .dataObjectId)
        try container.encode(dataObjectTemplateNameId, forKey: .dataObjectTemplateNameId)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(fields, forKey: .fields)
    }
}

