//
// RefreshAnalytics200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RefreshAnalytics200Response: Sendable, Codable, ParameterConvertible, Hashable {

    public var message: String
    public var refreshedAt: String

    public init(message: String, refreshedAt: String) {
        self.message = message
        self.refreshedAt = refreshedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case refreshedAt = "refreshed_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(refreshedAt, forKey: .refreshedAt)
    }
}

