//
// RunTriggerRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RunTriggerRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public var inputParameters: [String: JSONValue]?

    public init(inputParameters: [String: JSONValue]? = nil) {
        self.inputParameters = inputParameters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case inputParameters = "input_parameters"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(inputParameters, forKey: .inputParameters)
    }
}

