//
// SendInviteRequestInvitesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SendInviteRequestInvitesInner: Sendable, Codable, ParameterConvertible, Hashable {

    public var email: String
    public var roles: [String]?
    public var team: SendInviteRequestInvitesInnerTeam?

    public init(email: String, roles: [String]? = nil, team: SendInviteRequestInvitesInnerTeam? = nil) {
        self.email = email
        self.roles = roles
        self.team = team
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case roles
        case team
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(roles, forKey: .roles)
        try container.encodeIfPresent(team, forKey: .team)
    }
}

