//
// SignupNeeded200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SignupNeeded200Response: Sendable, Codable, ParameterConvertible, Hashable {

    public var signupNeeded: Bool

    public init(signupNeeded: Bool) {
        self.signupNeeded = signupNeeded
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case signupNeeded = "signup_needed"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(signupNeeded, forKey: .signupNeeded)
    }
}

