//
// TriggerExport200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TriggerExport200Response: Sendable, Codable, ParameterConvertible, Hashable {

    public var message: String
    public var exportId: String
    public var data: JSONValue?

    public init(message: String, exportId: String, data: JSONValue? = nil) {
        self.message = message
        self.exportId = exportId
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case exportId
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(exportId, forKey: .exportId)
        try container.encodeIfPresent(data, forKey: .data)
    }
}

