//
// TriggerExportRequestOneOfTracesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TriggerExportRequestOneOfTracesInner: Sendable, Codable, ParameterConvertible, Hashable {

    public var traceType: String
    public var attributes: [String: JSONValue]?
    public var elementIndices: [Double]

    public init(traceType: String, attributes: [String: JSONValue]? = nil, elementIndices: [Double]) {
        self.traceType = traceType
        self.attributes = attributes
        self.elementIndices = elementIndices
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case traceType = "trace_type"
        case attributes
        case elementIndices = "element_indices"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(traceType, forKey: .traceType)
        try container.encodeIfPresent(attributes, forKey: .attributes)
        try container.encode(elementIndices, forKey: .elementIndices)
    }
}

