//
// UpdateCustomTypeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateCustomTypeRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public var name: String
    public var description: String?
    public var properties: [String: UpdateCustomTypeRequestPropertiesValue]

    public init(name: String, description: String?, properties: [String: UpdateCustomTypeRequestPropertiesValue]) {
        self.name = name
        self.description = description
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case properties
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encode(properties, forKey: .properties)
    }
}

