//
// UpdateTriggerSecretsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateTriggerSecretsRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public var secretIds: [UUID]

    public init(secretIds: [UUID]) {
        self.secretIds = secretIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case secretIds = "secret_ids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(secretIds, forKey: .secretIds)
    }
}

