//
// UpdateConfigurationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateConfigurationRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public var name: String?
    public var configData: [String: JSONValue]?

    public init(name: String? = nil, configData: [String: JSONValue]? = nil) {
        self.name = name
        self.configData = configData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case configData = "config_data"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(configData, forKey: .configData)
    }
}

