//
// UpdateDataObjectTemplateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateDataObjectTemplateRequest: Sendable, Codable, ParameterConvertible, Hashable {

    public var objectName: String
    public var objectDisplayName: String
    public var objectDescription: String
    public var fields: [UpdateDataObjectTemplateRequestFieldsInner]
    public var isTemplate: Bool
    public var icons: [UpdateDataObjectTemplateRequestIconsInner]

    public init(objectName: String, objectDisplayName: String, objectDescription: String, fields: [UpdateDataObjectTemplateRequestFieldsInner], isTemplate: Bool, icons: [UpdateDataObjectTemplateRequestIconsInner]) {
        self.objectName = objectName
        self.objectDisplayName = objectDisplayName
        self.objectDescription = objectDescription
        self.fields = fields
        self.isTemplate = isTemplate
        self.icons = icons
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case objectName = "object_name"
        case objectDisplayName = "object_display_name"
        case objectDescription = "object_description"
        case fields
        case isTemplate = "is_template"
        case icons
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(objectName, forKey: .objectName)
        try container.encode(objectDisplayName, forKey: .objectDisplayName)
        try container.encode(objectDescription, forKey: .objectDescription)
        try container.encode(fields, forKey: .fields)
        try container.encode(isTemplate, forKey: .isTemplate)
        try container.encode(icons, forKey: .icons)
    }
}

