//
// UpdateDeployedWorkflowSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateDeployedWorkflowSchema: Sendable, Codable, ParameterConvertible, Hashable {

    public var companyId: String?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var createdBy: String?
    public var environment: String?
    public var typeRefId: String?
    public var revision: Double?
    public var workflowDescription: String?
    public var workflowName: String?
    public var resources: [SaveWorkflowRequestResourcesInner]?
    public var edges: [CreateDeployedWorkflowSchemaEdgesInner]?
    public var components: [CreateDeployedWorkflowSchemaComponentsInner]?
    public var objects: [CreateDeployedWorkflowSchemaObjectsInner]?
    public var renderOrder: [String]?
    public var icon: String?

    public init(companyId: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, createdBy: String? = nil, environment: String? = nil, typeRefId: String? = nil, revision: Double? = nil, workflowDescription: String? = nil, workflowName: String? = nil, resources: [SaveWorkflowRequestResourcesInner]? = nil, edges: [CreateDeployedWorkflowSchemaEdgesInner]? = nil, components: [CreateDeployedWorkflowSchemaComponentsInner]? = nil, objects: [CreateDeployedWorkflowSchemaObjectsInner]? = nil, renderOrder: [String]? = nil, icon: String? = nil) {
        self.companyId = companyId
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.createdBy = createdBy
        self.environment = environment
        self.typeRefId = typeRefId
        self.revision = revision
        self.workflowDescription = workflowDescription
        self.workflowName = workflowName
        self.resources = resources
        self.edges = edges
        self.components = components
        self.objects = objects
        self.renderOrder = renderOrder
        self.icon = icon
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case companyId = "company_id"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case createdBy = "created_by"
        case environment
        case typeRefId = "type_ref_id"
        case revision
        case workflowDescription = "workflow_description"
        case workflowName = "workflow_name"
        case resources
        case edges
        case components
        case objects
        case renderOrder = "render_order"
        case icon
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(companyId, forKey: .companyId)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(createdBy, forKey: .createdBy)
        try container.encodeIfPresent(environment, forKey: .environment)
        try container.encodeIfPresent(typeRefId, forKey: .typeRefId)
        try container.encodeIfPresent(revision, forKey: .revision)
        try container.encodeIfPresent(workflowDescription, forKey: .workflowDescription)
        try container.encodeIfPresent(workflowName, forKey: .workflowName)
        try container.encodeIfPresent(resources, forKey: .resources)
        try container.encodeIfPresent(edges, forKey: .edges)
        try container.encodeIfPresent(components, forKey: .components)
        try container.encodeIfPresent(objects, forKey: .objects)
        try container.encodeIfPresent(renderOrder, forKey: .renderOrder)
        try container.encodeIfPresent(icon, forKey: .icon)
    }
}

