//
// Whoami200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Whoami200Response: Sendable, Codable, ParameterConvertible, Hashable {

    public var email: String
    public var companyId: String
    public var userId: String
    public var orgId: String
    public var role: String?
    public var teamId: String?
    public var memberId: String

    public init(email: String, companyId: String, userId: String, orgId: String, role: String? = nil, teamId: String? = nil, memberId: String) {
        self.email = email
        self.companyId = companyId
        self.userId = userId
        self.orgId = orgId
        self.role = role
        self.teamId = teamId
        self.memberId = memberId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case companyId = "company_id"
        case userId = "user_id"
        case orgId = "org_id"
        case role
        case teamId = "team_id"
        case memberId = "member_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encode(companyId, forKey: .companyId)
        try container.encode(userId, forKey: .userId)
        try container.encode(orgId, forKey: .orgId)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(teamId, forKey: .teamId)
        try container.encode(memberId, forKey: .memberId)
    }
}

