//
// DebugLogAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class DebugLogAPI {

    /**
     Request a pre-signed URL for uploading a debug log file
     
     - parameter key: (query)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: GetUploadUrl200Response
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getUploadUrl(key: String, apiConfiguration: Cloneable_Swift_ClientAPIConfiguration = Cloneable_Swift_ClientAPIConfiguration.shared) async throws(ErrorResponse) -> GetUploadUrl200Response {
        return try await getUploadUrlWithRequestBuilder(key: key, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Request a pre-signed URL for uploading a debug log file
     - GET /debug-logs/upload-url
     - parameter key: (query)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<GetUploadUrl200Response> 
     */
    open class func getUploadUrlWithRequestBuilder(key: String, apiConfiguration: Cloneable_Swift_ClientAPIConfiguration = Cloneable_Swift_ClientAPIConfiguration.shared) -> RequestBuilder<GetUploadUrl200Response> {
        let localVariablePath = "/debug-logs/upload-url"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "key": (wrappedValue: key.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetUploadUrl200Response>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
