//
// AuthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AuthAPI {

    /**
     Create and sync orgs to auth platform for new accounts
     
     - parameter signupCreateOrgRequest: (body) Body (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func signupCreateOrg(signupCreateOrgRequest: SignupCreateOrgRequest? = nil, apiResponseQueue: DispatchQueue = Cloneable_Swift_ClientAPI.apiResponseQueue, completion: @escaping ((_ data: SignupCreateOrg200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return signupCreateOrgWithRequestBuilder(signupCreateOrgRequest: signupCreateOrgRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create and sync orgs to auth platform for new accounts
     - POST /auth/signup/create-org
     - parameter signupCreateOrgRequest: (body) Body (optional)
     - returns: RequestBuilder<SignupCreateOrg200Response> 
     */
    open class func signupCreateOrgWithRequestBuilder(signupCreateOrgRequest: SignupCreateOrgRequest? = nil) -> RequestBuilder<SignupCreateOrg200Response> {
        let localVariablePath = "/auth/signup/create-org"
        let localVariableURLString = Cloneable_Swift_ClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: signupCreateOrgRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SignupCreateOrg200Response>.Type = Cloneable_Swift_ClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Create and sync users to auth platform for new accounts
     
     - parameter signupCreateUserRequest: (body) Body (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func signupCreateUser(signupCreateUserRequest: SignupCreateUserRequest? = nil, apiResponseQueue: DispatchQueue = Cloneable_Swift_ClientAPI.apiResponseQueue, completion: @escaping ((_ data: SignupCreateUser200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return signupCreateUserWithRequestBuilder(signupCreateUserRequest: signupCreateUserRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Create and sync users to auth platform for new accounts
     - POST /auth/signup/create-user
     - parameter signupCreateUserRequest: (body) Body (optional)
     - returns: RequestBuilder<SignupCreateUser200Response> 
     */
    open class func signupCreateUserWithRequestBuilder(signupCreateUserRequest: SignupCreateUserRequest? = nil) -> RequestBuilder<SignupCreateUser200Response> {
        let localVariablePath = "/auth/signup/create-user"
        let localVariableURLString = Cloneable_Swift_ClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: signupCreateUserRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SignupCreateUser200Response>.Type = Cloneable_Swift_ClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Check if signup is needed
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func signupNeeded(apiResponseQueue: DispatchQueue = Cloneable_Swift_ClientAPI.apiResponseQueue, completion: @escaping ((_ data: SignupNeeded200Response?, _ error: Error?) -> Void)) -> RequestTask {
        return signupNeededWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Check if signup is needed
     - GET /auth/signup-needed
     - returns: RequestBuilder<SignupNeeded200Response> 
     */
    open class func signupNeededWithRequestBuilder() -> RequestBuilder<SignupNeeded200Response> {
        let localVariablePath = "/auth/signup-needed"
        let localVariableURLString = Cloneable_Swift_ClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SignupNeeded200Response>.Type = Cloneable_Swift_ClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
