name: Cloneable_Swift_API
targets:
  Cloneable_Swift_API:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [Cloneable_Swift_API]
    info:
      path: ./Info.plist
      version: 0.0.1
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
    - carthage: Alamofire
