name: Swift_API_Client
targets:
  Swift_API_Client:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [Swift_API_Client]
    info:
      path: ./Info.plist
      version: 0.0.1
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
    - carthage: Alamofire
