name: Cloneable_Swift_ClientCloneable_Swift_Client
targets:
  Cloneable_Swift_ClientCloneable_Swift_Client:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [Cloneable_Swift_ClientCloneable_Swift_Client]
    info:
      path: ./Info.plist
      version: 0.0.1
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
    - carthage: Alamofire
