//
// ApiKeySchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiKeySchema: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var keyHash: String
    public var role: String
    public var expiration: Date
    public var createdAt: Date
    public var createdBy: String
    public var companyId: String
    public var deactivatedAt: Date?

    public init(id: UUID, keyHash: String, role: String, expiration: Date, createdAt: Date, createdBy: String, companyId: String, deactivatedAt: Date?) {
        self.id = id
        self.keyHash = keyHash
        self.role = role
        self.expiration = expiration
        self.createdAt = createdAt
        self.createdBy = createdBy
        self.companyId = companyId
        self.deactivatedAt = deactivatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case keyHash = "key_hash"
        case role
        case expiration
        case createdAt = "created_at"
        case createdBy = "created_by"
        case companyId = "company_id"
        case deactivatedAt = "deactivated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(keyHash, forKey: .keyHash)
        try container.encode(role, forKey: .role)
        try container.encode(expiration, forKey: .expiration)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(createdBy, forKey: .createdBy)
        try container.encode(companyId, forKey: .companyId)
        try container.encode(deactivatedAt, forKey: .deactivatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ApiKeySchema: Identifiable {}
