//
// ArchiveDataObjects200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ArchiveDataObjects200Response: Codable, JSONEncodable, Hashable {

    public var archivedIds: [String]

    public init(archivedIds: [String]) {
        self.archivedIds = archivedIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case archivedIds = "archived_ids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(archivedIds, forKey: .archivedIds)
    }
}

