//
// CancelInviteRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CancelInviteRequest: Codable, JSONEncodable, Hashable {

    public var email: String
    public var orgId: String?

    public init(email: String, orgId: String? = nil) {
        self.email = email
        self.orgId = orgId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case orgId = "org_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(orgId, forKey: .orgId)
    }
}

