//
// ChangeTeamRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChangeTeamRequest: Codable, JSONEncodable, Hashable {

    public var teamId: String

    public init(teamId: String) {
        self.teamId = teamId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case teamId = "team_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(teamId, forKey: .teamId)
    }
}

