//
// CompileWorkflowRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CompileWorkflowRequest: Codable, JSONEncodable, Hashable {

    public var workflow: CompileWorkflowRequestWorkflow

    public init(workflow: CompileWorkflowRequestWorkflow) {
        self.workflow = workflow
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case workflow
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(workflow, forKey: .workflow)
    }
}

