//
// CreateCompletedWorkflowSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCompletedWorkflowSchema: Codable, JSONEncodable, Hashable {

    public var name: String
    public var companyId: String
    public var finalized: Bool
    public var finalizedAt: String?
    public var createdAt: String
    public var createdBy: String
    public var updatedAt: Date?
    public var typeRefId: String
    public var relatedObjectTypes: [CompletedWorkflowSchemaRelatedObjectTypesInner]?
    public var workflowInstanceId: String
    public var auditTimeline: [CompletedWorkflowSchemaAuditTimelineInner]?

    public init(name: String, companyId: String, finalized: Bool, finalizedAt: String? = nil, createdAt: String, createdBy: String, updatedAt: Date? = nil, typeRefId: String, relatedObjectTypes: [CompletedWorkflowSchemaRelatedObjectTypesInner]? = nil, workflowInstanceId: String, auditTimeline: [CompletedWorkflowSchemaAuditTimelineInner]? = nil) {
        self.name = name
        self.companyId = companyId
        self.finalized = finalized
        self.finalizedAt = finalizedAt
        self.createdAt = createdAt
        self.createdBy = createdBy
        self.updatedAt = updatedAt
        self.typeRefId = typeRefId
        self.relatedObjectTypes = relatedObjectTypes
        self.workflowInstanceId = workflowInstanceId
        self.auditTimeline = auditTimeline
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case companyId = "company_id"
        case finalized
        case finalizedAt = "finalized_at"
        case createdAt = "created_at"
        case createdBy = "created_by"
        case updatedAt = "updated_at"
        case typeRefId = "type_ref_id"
        case relatedObjectTypes = "related_object_types"
        case workflowInstanceId = "workflow_instance_id"
        case auditTimeline = "audit_timeline"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(companyId, forKey: .companyId)
        try container.encode(finalized, forKey: .finalized)
        try container.encodeIfPresent(finalizedAt, forKey: .finalizedAt)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(createdBy, forKey: .createdBy)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encode(typeRefId, forKey: .typeRefId)
        try container.encodeIfPresent(relatedObjectTypes, forKey: .relatedObjectTypes)
        try container.encode(workflowInstanceId, forKey: .workflowInstanceId)
        try container.encodeIfPresent(auditTimeline, forKey: .auditTimeline)
    }
}

