//
// CreateFile409Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateFile409Response: Codable, JSONEncodable, Hashable {

    public var message: String
    public var id: String
    public var uploadUrl: String

    public init(message: String, id: String, uploadUrl: String) {
        self.message = message
        self.id = id
        self.uploadUrl = uploadUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case id
        case uploadUrl = "upload_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(id, forKey: .id)
        try container.encode(uploadUrl, forKey: .uploadUrl)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension CreateFile409Response: Identifiable {}
