//
// CreateCustomTypeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateCustomTypeRequest: Codable, JSONEncodable, Hashable {

    public var name: String
    public var description: String?
    public var properties: [String: AnyCodable]?

    public init(name: String, description: String? = nil, properties: [String: AnyCodable]? = nil) {
        self.name = name
        self.description = description
        self.properties = properties
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case properties
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(properties, forKey: .properties)
    }
}

