//
// CreateModelConversionJobRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateModelConversionJobRequest: Codable, JSONEncodable, Hashable {

    public var originModelId: String
    public var exportFormat: String
    public var params: [CreateModelConversionJobRequestParamsInner]

    public init(originModelId: String, exportFormat: String, params: [CreateModelConversionJobRequestParamsInner]) {
        self.originModelId = originModelId
        self.exportFormat = exportFormat
        self.params = params
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case originModelId = "origin_model_id"
        case exportFormat = "export_format"
        case params
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(originModelId, forKey: .originModelId)
        try container.encode(exportFormat, forKey: .exportFormat)
        try container.encode(params, forKey: .params)
    }
}

