//
// DataObjectSchemaRelatedWorkflowInstanceIdsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DataObjectSchemaRelatedWorkflowInstanceIdsInner: Codable, JSONEncodable, Hashable {

    public var workflowFinalized: Bool
    public var workflowInstanceId: String
    public var workflowName: String

    public init(workflowFinalized: Bool, workflowInstanceId: String, workflowName: String) {
        self.workflowFinalized = workflowFinalized
        self.workflowInstanceId = workflowInstanceId
        self.workflowName = workflowName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case workflowFinalized = "workflow_finalized"
        case workflowInstanceId = "workflow_instance_id"
        case workflowName = "workflow_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(workflowFinalized, forKey: .workflowFinalized)
        try container.encode(workflowInstanceId, forKey: .workflowInstanceId)
        try container.encode(workflowName, forKey: .workflowName)
    }
}

