//
// GetDeployedWorkflowsQueryFiltersParameter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetDeployedWorkflowsQueryFiltersParameter: Codable, JSONEncodable, Hashable {

    public var createdBy: String?
    public var createdAt: String?
    public var typeRefId: String?
    public var environment: String?

    public init(createdBy: String? = nil, createdAt: String? = nil, typeRefId: String? = nil, environment: String? = nil) {
        self.createdBy = createdBy
        self.createdAt = createdAt
        self.typeRefId = typeRefId
        self.environment = environment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdBy = "created_by"
        case createdAt = "created_at"
        case typeRefId = "type_ref_id"
        case environment
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(createdBy, forKey: .createdBy)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(typeRefId, forKey: .typeRefId)
        try container.encodeIfPresent(environment, forKey: .environment)
    }
}

