//
// GetDataObjectsPaged200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetDataObjectsPaged200Response: Codable, JSONEncodable, Hashable {

    public var index: Int
    public var size: Int
    public var count: Int
    public var pages: Int
    public var items: [DataObjectSchema]

    public init(index: Int, size: Int, count: Int, pages: Int, items: [DataObjectSchema]) {
        self.index = index
        self.size = size
        self.count = count
        self.pages = pages
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case index
        case size
        case count
        case pages
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(index, forKey: .index)
        try container.encode(size, forKey: .size)
        try container.encode(count, forKey: .count)
        try container.encode(pages, forKey: .pages)
        try container.encode(items, forKey: .items)
    }
}

