//
// GetDataObjectsPaged200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetDataObjectsPaged200Response: Codable, JSONEncodable, Hashable {

    public var index: Double?
    public var size: Double?
    public var count: Double?
    public var pages: Double?
    public var items: [DataObjectSchema]?

    public init(index: Double? = nil, size: Double? = nil, count: Double? = nil, pages: Double? = nil, items: [DataObjectSchema]? = nil) {
        self.index = index
        self.size = size
        self.count = count
        self.pages = pages
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case index
        case size
        case count
        case pages
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(index, forKey: .index)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(pages, forKey: .pages)
        try container.encodeIfPresent(items, forKey: .items)
    }
}

