//
// GetManyFilesFiltersParameter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetManyFilesFiltersParameter: Codable, JSONEncodable, Hashable {

    public var createdBy: String?
    public var createdAt: GetManyFilesFiltersParameterCreatedAt?
    public var type: [String]?
    public var savedToCloud: Bool?
    public var syncToEdge: Bool?
    public var search: String?

    public init(createdBy: String? = nil, createdAt: GetManyFilesFiltersParameterCreatedAt? = nil, type: [String]? = nil, savedToCloud: Bool? = nil, syncToEdge: Bool? = nil, search: String? = nil) {
        self.createdBy = createdBy
        self.createdAt = createdAt
        self.type = type
        self.savedToCloud = savedToCloud
        self.syncToEdge = syncToEdge
        self.search = search
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdBy = "created_by"
        case createdAt = "created_at"
        case type
        case savedToCloud = "saved_to_cloud"
        case syncToEdge = "sync_to_edge"
        case search
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(createdBy, forKey: .createdBy)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(savedToCloud, forKey: .savedToCloud)
        try container.encodeIfPresent(syncToEdge, forKey: .syncToEdge)
        try container.encodeIfPresent(search, forKey: .search)
    }
}

