//
// GetOneExecution200ResponseInputs.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetOneExecution200ResponseInputs: Codable, JSONEncodable, Hashable {

    public var parameters: [GetOneExecution200ResponseInputsParametersInner]

    public init(parameters: [GetOneExecution200ResponseInputsParametersInner]) {
        self.parameters = parameters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case parameters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(parameters, forKey: .parameters)
    }
}

