//
// GetOrgWithUsers200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetOrgWithUsers200Response: Codable, JSONEncodable, Hashable {

    public var org: CurrentOrg200Response
    public var users: [GetOrgWithUsers200ResponseUsersInner]

    public init(org: CurrentOrg200Response, users: [GetOrgWithUsers200ResponseUsersInner]) {
        self.org = org
        self.users = users
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case org
        case users
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(org, forKey: .org)
        try container.encode(users, forKey: .users)
    }
}

