//
// GetPagedWorkflowsSortingParameter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetPagedWorkflowsSortingParameter: Codable, JSONEncodable, Hashable {

    public enum Column: String, Codable, CaseIterable {
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
    public var column: Column
    public var desc: Bool

    public init(column: Column, desc: Bool) {
        self.column = column
        self.desc = desc
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case column
        case desc
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(column, forKey: .column)
        try container.encode(desc, forKey: .desc)
    }
}

