//
// GetSuggestions200ResponseSuggestionsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetSuggestions200ResponseSuggestionsInner: Codable, JSONEncodable, Hashable {

    public var text: String
    public var magicKey: String
    public var isCollection: Bool

    public init(text: String, magicKey: String, isCollection: Bool) {
        self.text = text
        self.magicKey = magicKey
        self.isCollection = isCollection
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case text
        case magicKey
        case isCollection
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(text, forKey: .text)
        try container.encode(magicKey, forKey: .magicKey)
        try container.encode(isCollection, forKey: .isCollection)
    }
}

