//
// IssueKeyForCustomAuthRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IssueKeyForCustomAuthRequest: Codable, JSONEncodable, Hashable {

    public var jwt: String
    public var firstName: String
    public var lastName: String
    public var orgId: String
    public var orgSlug: String

    public init(jwt: String, firstName: String, lastName: String, orgId: String, orgSlug: String) {
        self.jwt = jwt
        self.firstName = firstName
        self.lastName = lastName
        self.orgId = orgId
        self.orgSlug = orgSlug
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jwt
        case firstName = "first_name"
        case lastName = "last_name"
        case orgId = "org_id"
        case orgSlug = "org_slug"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(jwt, forKey: .jwt)
        try container.encode(firstName, forKey: .firstName)
        try container.encode(lastName, forKey: .lastName)
        try container.encode(orgId, forKey: .orgId)
        try container.encode(orgSlug, forKey: .orgSlug)
    }
}

