//
// OrgSchemaCreate.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrgSchemaCreate: Codable, JSONEncodable, Hashable {

    public static let idRule = StringRule(minLength: nil, maxLength: 225, pattern: nil)
    public static let nameRule = StringRule(minLength: nil, maxLength: 255, pattern: nil)
    public static let organizationIdRule = StringRule(minLength: nil, maxLength: 225, pattern: nil)
    public static let roboflowApiKeyRule = StringRule(minLength: nil, maxLength: 225, pattern: nil)
    public var key: UUID?
    public var id: String
    public var name: String
    public var createdAt: Date?
    public var updatedAt: Date?
    public var organizationId: String?
    public var roboflowApiKey: String?

    public init(key: UUID? = nil, id: String, name: String, createdAt: Date? = nil, updatedAt: Date? = nil, organizationId: String? = nil, roboflowApiKey: String? = nil) {
        self.key = key
        self.id = id
        self.name = name
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.organizationId = organizationId
        self.roboflowApiKey = roboflowApiKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case id
        case name
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case organizationId = "organization_id"
        case roboflowApiKey = "roboflow_api_key"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(key, forKey: .key)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(organizationId, forKey: .organizationId)
        try container.encodeIfPresent(roboflowApiKey, forKey: .roboflowApiKey)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension OrgSchemaCreate: Identifiable {}
