//
// SaveWorkflowRequestWorkflowResourcesInnerObjectsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SaveWorkflowRequestWorkflowResourcesInnerObjectsInner: Codable, JSONEncodable, Hashable {

    public var templateId: String
    public var createdAfter: String?

    public init(templateId: String, createdAfter: String? = nil) {
        self.templateId = templateId
        self.createdAfter = createdAfter
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case templateId = "template_id"
        case createdAfter = "created_after"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(templateId, forKey: .templateId)
        try container.encodeIfPresent(createdAfter, forKey: .createdAfter)
    }
}

