//
// SendInviteRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SendInviteRequest: Codable, JSONEncodable, Hashable {

    public var invites: [SendInviteRequestInvitesInner]
    public var orgId: String?

    public init(invites: [SendInviteRequestInvitesInner], orgId: String? = nil) {
        self.invites = invites
        self.orgId = orgId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case invites
        case orgId = "org_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(invites, forKey: .invites)
        try container.encodeIfPresent(orgId, forKey: .orgId)
    }
}

