//
// SignupCreateUserRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SignupCreateUserRequest: Codable, JSONEncodable, Hashable {

    public var orgName: SignupCreateUserRequestOrgName?
    public var orgId: String
    public var firstName: String
    public var lastName: String
    public var phone: SignupCreateUserRequestPhone?

    public init(orgName: SignupCreateUserRequestOrgName? = nil, orgId: String, firstName: String, lastName: String, phone: SignupCreateUserRequestPhone? = nil) {
        self.orgName = orgName
        self.orgId = orgId
        self.firstName = firstName
        self.lastName = lastName
        self.phone = phone
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orgName = "org_name"
        case orgId = "org_id"
        case firstName = "first_name"
        case lastName = "last_name"
        case phone
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(orgName, forKey: .orgName)
        try container.encode(orgId, forKey: .orgId)
        try container.encode(firstName, forKey: .firstName)
        try container.encode(lastName, forKey: .lastName)
        try container.encodeIfPresent(phone, forKey: .phone)
    }
}

