//
// SignupCreateOrgRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SignupCreateOrgRequest: Codable, JSONEncodable, Hashable {

    public var orgId: String
    public var orgName: String
    public var userFirstName: String
    public var userLastName: String

    public init(orgId: String, orgName: String, userFirstName: String, userLastName: String) {
        self.orgId = orgId
        self.orgName = orgName
        self.userFirstName = userFirstName
        self.userLastName = userLastName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orgId = "org_id"
        case orgName = "org_name"
        case userFirstName = "user_first_name"
        case userLastName = "user_last_name"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(orgId, forKey: .orgId)
        try container.encode(orgName, forKey: .orgName)
        try container.encode(userFirstName, forKey: .userFirstName)
        try container.encode(userLastName, forKey: .userLastName)
    }
}

