//
// SyncDataObject500Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SyncDataObject500Response: Codable, JSONEncodable, Hashable {

    public var error: String
    public var failedIds: [String]

    public init(error: String, failedIds: [String]) {
        self.error = error
        self.failedIds = failedIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case failedIds = "failed_ids"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(error, forKey: .error)
        try container.encode(failedIds, forKey: .failedIds)
    }
}

