//
// TriggerExecutionStopRequestLogsInnerMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TriggerExecutionStopRequestLogsInnerMetadata: Codable, JSONEncodable, Hashable {

    public var source: String?
    public var correlationId: String?
    public var additionalContext: [String: AnyCodable]?

    public init(source: String?, correlationId: String?, additionalContext: [String: AnyCodable]?) {
        self.source = source
        self.correlationId = correlationId
        self.additionalContext = additionalContext
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case source
        case correlationId = "correlation_id"
        case additionalContext = "additional_context"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(source, forKey: .source)
        try container.encode(correlationId, forKey: .correlationId)
        try container.encode(additionalContext, forKey: .additionalContext)
    }
}

