//
// TriggerExportRequestOneOfAttachmentsInnerPixelSelectionInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TriggerExportRequestOneOfAttachmentsInnerPixelSelectionInner: Codable, JSONEncodable, Hashable {

    public var percentX: Double
    public var percentY: Double

    public init(percentX: Double, percentY: Double) {
        self.percentX = percentX
        self.percentY = percentY
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case percentX
        case percentY
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(percentX, forKey: .percentX)
        try container.encode(percentY, forKey: .percentY)
    }
}

