//
// UpdateDataObjectTemplateRequestFieldsInnerRequiredFor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateDataObjectTemplateRequestFieldsInnerRequiredFor: Codable, JSONEncodable, Hashable {

    public var completion: Bool? = false
    public var creation: Bool? = false

    public init(completion: Bool? = false, creation: Bool? = false) {
        self.completion = completion
        self.creation = creation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case completion
        case creation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(completion, forKey: .completion)
        try container.encodeIfPresent(creation, forKey: .creation)
    }
}

