//
// UpdateCustomTypeRequestPropertiesValueOneOfInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateCustomTypeRequestPropertiesValueOneOfInner: Codable, JSONEncodable, Hashable {

    public var title: String
    public var value: UpdateCustomTypeRequestPropertiesValueOneOfInnerValue

    public init(title: String, value: UpdateCustomTypeRequestPropertiesValueOneOfInnerValue) {
        self.title = title
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(value, forKey: .value)
    }
}

