//
// OrgResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OrgResponse: Codable, JSONEncodable, Hashable {

    public var id: String
    public var name: String
    public var createdAt: String
    public var updatedAt: String
    public var roles: [String]
    public var users: [String]

    public init(id: String, name: String, createdAt: String, updatedAt: String, roles: [String], users: [String]) {
        self.id = id
        self.name = name
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.roles = roles
        self.users = users
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case roles
        case users
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(roles, forKey: .roles)
        try container.encode(users, forKey: .users)
    }
}

